import { chromium } from 'playwright-core';
import { serve } from './lib.mjs';
const { server, port } = await serve();
const browser = await chromium.launch({ channel: 'chrome', args: ['--enable-unsafe-swiftshader','--hide-scrollbars'] });
const ctx = await browser.newContext({ viewport:{width:390,height:844}, hasTouch:true, isMobile:true, deviceScaleFactor:1 });
const page = await ctx.newPage();
await page.goto(`http://127.0.0.1:${port}/index.html?skipIntro`, { waitUntil:'load', timeout:120000 });
await page.waitForFunction('window.__WALLY_READY__===true',{timeout:120000});
await page.waitForTimeout(3500);
const cdp = await ctx.newCDPSession(page);
const tap = async (x,y)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1,radiusX:14,radiusY:14,force:1}]});await page.waitForTimeout(70);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(600);};
await page.evaluate(()=>{const u=WALLY.ctx.ui;u.closeAll();u.setTouch(false);u.setHideUI(true);
  window.__log=[];
  for(const t of ['pointerdown','touchstart','click'])document.addEventListener(t,(e)=>window.__log.push(t+':'+(e.target.className||e.target.tagName)+(e.defaultPrevented?'(prev)':'')),true);});
await page.waitForTimeout(700);
const state=(l)=>page.evaluate((L)=>({label:L,pad:WALLY.ctx.ui.touch.enabled,hide:WALLY.ctx.ui.hideUI,panels:WALLY.ctx.ui.panels,log:window.__log.slice()}),l);
console.log(JSON.stringify(await state('before')));
await tap(341,810); console.log('tap1', JSON.stringify(await state('after tap1')));
await tap(341,810); console.log('tap2', JSON.stringify(await state('after tap2')));
await browser.close(); server.close();
