import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
const ROOT='/Users/herwig/Documents/GitHub/wallyrpg';
const M={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8'};
const s=createServer(async(rq,rs)=>{try{const c=decodeURIComponent(rq.url.split('?')[0]);
const b=await readFile(join(ROOT,c==='/'?'index.html':c));rs.writeHead(200,{'content-type':M[extname(c)]||'application/octet-stream'});rs.end(b);}catch{rs.writeHead(404).end();}});
await new Promise(r=>s.listen(0,'127.0.0.1',r)); const P=s.address().port;
const br=await chromium.launch({channel:'chrome',args:['--enable-unsafe-swiftshader','--hide-scrollbars','--mute-audio']});
const pg=await br.newPage({viewport:{width:1400,height:820}});
await pg.goto(`http://127.0.0.1:${P}/index.html?skipIntro`,{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__WALLY_READY__===true',{timeout:180000});
await pg.waitForTimeout(3500);
await pg.keyboard.press("KeyM");
await pg.waitForTimeout(1200);
const txt = await pg.evaluate(()=>document.body.innerText);
console.log('--- PLACES APP AT BOOT ---'); console.log(txt.slice(0,800));
await pg.screenshot({path: join(ROOT,'shots','vj-places-boot.png')});
// click the apartment card
const clicked = await pg.evaluate(()=>{const bs=[...document.querySelectorAll('button')];
  const t=bs.find(b=>/Apartment/i.test(b.innerText)); if(!t) return 'not found'; t.click(); return t.innerText.replace(/\n/g,' | ');});
console.log('clicked card:', clicked);
await pg.waitForTimeout(1500);
console.log('--- AFTER CLICK ---'); console.log((await pg.evaluate(()=>document.body.innerText)).slice(0,500));
console.log('pos:', await pg.evaluate(()=>{const w=window.WALLY.ctx.wally.root.position;return [+w.x.toFixed(1),+w.z.toFixed(1)];}));
await br.close(); s.close();
